version: "3.9"
services:
  mysql:
    image: mysql:8.0
    container_name: o2o_mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: identity
      MYSQL_USER: app
      MYSQL_PASSWORD: app123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 2s
      retries: 20

  redis:
    image: redis:7-alpine
    container_name: o2o_redis
    restart: unless-stopped
    ports:
      - "6380:6379"

volumes:
  mysql_data:
